### PR TITLE
fixed docker in docker compilation

### PR DESCRIPTION
**Pull request by AlexHaxe**
I've added lix to outside and compilation container, cleaned up some files.

application container does not have haxe or ability to compile, app compilation takes place outside, while program / sample compilation happens in compiler container. that makes things a lot simpler.
I think it's to slow for completion (around 3s between pressing `Build + Run` and results), not sure if we should provide completion from application container and only do compiles in second docker. 

I've added Hashlink and eval targets. for Hashlink `hl`, `libhl.so` and `*.hdll` files need to sit in `hashlink-bin` folder (compiled for Ubuntu 20.04). we could add a `Dockerfile` to build binaries and prepare that folder. 

`lixSetup` is where all Haxe versions and libs go. it has a `haxe` folder which is basically a lix home / repository folder and a `haxe_libraries` folder which is what ends up in programe's / sample's compilation folder.

I think for frontend libs (JS) we could try to install them via npm (or some other package manager), so that we don't need to check them in (reduces changelists when switching to newer versions). 

(edit: I've stopped myself from formatting the code, to make PRs not too messy)

### CODE REVIEW

**Comment by AlexHaxe** [comment]
my recent commit removes most of the lib stuff and uses `npm i` to install them fresh.
I've updated to latest codemirror, a newer bootstrap and jquery (not latest, they have some relationship), three.js and pixi.js. I also updated stats.js but that might be unused. 

I haven't seen any errors or weirdness, so maybe they are fine?!

**Comment by AlexHaxe** [comment]
I've fixed a few minor issues and merged changes from @clemos's master branch to keep it compatible.

**Comment by RblSb** [comment]
Oh, for some reason i didn't receive notifications for this repo, just found this accidentally. I would like to format this with haxe formatter default style, btw. Some problems with moving dockerd setup part to Dockerfile?

**Comment by AlexHaxe** [comment]
no problem, it gave me time to fix a few things.

formatter is fine with me :) - I didn't apply it because it would have made an already large changelist even larger. feel free to run it through formatter.

dockerd setup didn't really work. docker doesn't provide a service script for Ubuntu 20.04 and running it from Dockerfile doesn't seem to launch it persistently (hence the manual step). the reason I chose Ubuntu 20.04 for both is that my hashlink binary wouldn't work inside the original container. if we add a intermediate hashlink compilation container then we could chose a docker image base that is a bit leaner than Ubuntu (I usually use debian based distros like Ubuntu, so I'm most familiar with those, but I can probably adapt to something else).
I guess some of the slow response time for Haxe compilation is due to launching a larger than necessary docker image and running node / lix probably adds to it as well. I reduced some of the time by generating a lix scope in code. 

I haven't checked the timings when forwarding docker.sock to container, but when we do that then container has to know absolute paths from outside of it which is less ideal. I am not sure what is the best approach here.

**Comment by RblSb** [comment]
What i'm getting inside files like `http://127.0.0.1:623/lib/codemirror/lib/codemirror.js` and other lib/*.js stuff (Haxe 4.1.5):
```
<br />
<b>Fatal error</b>:  Uncaught haxe\ValueException: DENotFound(lib) in /var/www/html/app/lib/haxe/Exception.php:95
Stack trace:
#0 /var/www/html/app/lib/haxe/web/Dispatch.php(485): haxe\Exception::thrown()
#1 /var/www/html/app/lib/App.php(68): haxe\web\Dispatch-&gt;runtimeDispatch()
#2 /var/www/html/app/index.php(13): App::main()
#3 {main}
  thrown in <b>/var/www/html/app/lib/haxe/Exception.php</b> on line <b>95</b><br />
```
Some ideas?

**Comment by RblSb** [comment]
Fixed it with running `haxe -x PostinstallLibs` manually. This should be done by Lix or npm install step is missed?
Now i can press build, around ten seconds on mbp 2012 to get result, but build error is `haxelib path: /root/haxe/versions/4.1.5/haxelib: 1: Syntax error: "(" unexpected`. Can be related to macos host tho.

**Comment by AlexHaxe** [comment]
running `npm i` should donwload all external libs and then automatically invoke `haxe -x PostinstallLibs` which copies them from `node_modules` folder to `www/lib` folder.

after that you prepare `lixSetup` folder by 
```bash
cd lixSetup
export HAXESHIM_ROOT=$PWD/haxe
lix download
lix install haxe 4.0.5
lix install haxe 3.4.7
etc.
```
`export HAXESHIM_ROOT` should make lix use `lixSetup/haxe` folder for its cache (instead of using `~/haxe`) and then `lix download` should download all haxelibs from `haxe_libraries` folder. after that `lix install haxe` install additional Haxe versions.
you might have to to use npx prefix (`npx lix ...`) if you don't have a globally installed lix version (not sure if that requires a `ln -s ../node_modules .`).

10 seconds is a very long time for a compilation run. I get around 2-3 seconds, but i'm running an Ubuntu 20.04. maybe some smaller container images might help speed things up.

**Comment by RblSb** [comment]
Nah, everything is fine, except build failures and my old cpu.
Just thinking if something like [firejail](https://github.com/netblue30/firejail) can be better here.
Looks like it can in theory run haxe process with temporal virtual fs, ram/cpu time limit and file size limit. What do you think?

**Comment by AlexHaxe** [comment]
I don't have any experience with firejail, it sounds interesting. but if it doesn't run inside docker then it doesn't really help.

I've experimented with running with docker.sock mapped from outside, so that compiler docker instances run on main dockerd. at first i would get error 126 when trying to compile but that was due to www-data user's id from inside had no access permisson to talk to docker.sock (I think you had a similar issue somewhere). after I adjusted permissions it would run and compile, and build times where down to around 1s. 
I'm not sure how secure such a setup is, since inside / web container needs to know absolute paths from outside, which feels less secure.

**Comment by AlexHaxe** [comment]
I've tried using an alpine base docker image for compilation container and at least on my local system it is slightly faster than the ubuntu based version. unfortunately on benchmark server it doesn't seem to make any difference

maybe you want to give it a try:
```Dockerfile
FROM frolvlad/alpine-glibc
WORKDIR /srv/program
RUN apk add nodejs npm
RUN npm install --global lix || true
RUN echo "/root/haxe/haxelib" > /root/.haxelib 
```

**Comment by RblSb** [comment]
Yay, 2 seconds, if this actually runs container
image

**Comment by AlexHaxe** [comment]
Build failure doesn't sound too good... 


I've check benchmark server and it seems I didn't import the correct image when testing alpine version. it's a few hundred milliseconds faster with alpine compared to an ubuntu image. so it does something, but not as much as I hoped.

I've also come up with a Docker image that builds hashlink (though it needs an additional `musl` packaged installed in compiler image [updated in previous post]) :
```Dockerfile
FROM frolvlad/alpine-glibc
WORKDIR /srv/program
RUN apk add --no-cache ca-certificates build-base gcc g++ pcre pcre-dev git cmake make libpng-dev openal-soft-dev sdl2-dev mbedtls-dev libuv-dev libjpeg-turbo-dev libvorbis-dev glu-dev nodejs npm
RUN npm i lix --global
RUN lix scope create --global
RUN lix install --global haxe 4.1.5
RUN haxelib setup /root/haxe/haxelib
RUN haxelib install hashlink
CMD rm -rf hashlink; \
    git clone https://github.com/HaxeFoundation/hashlink.git; \
    cd hashlink; \
    cmake .;  \
    make; \
    cp bin/hl bin/libhl.so* bin/*.hdll /hashlink-bin/
```

**Comment by RblSb** [comment]
Maybe that `compiler docker instances run on main dockerd` would work for me, idk. If you think this is not safe or crossplatform too, i can try to define out that docker subcontainer for at least local try-haxe testing.

**Comment by AlexHaxe** [comment]
I've been toying with a new idea: what if we run a web and a compilation container in main dockerd, with both of them running constantly. 
for compilation runs web app executes something like `docker exec instance_name sh -c "cd programs/<uid>; haxe…"`, so it reuses compilation container instance over and over.

my local tests have shown that it can achieve compilation times of about one second or below. also completion works fast enough to be usable.

the only caveat I see would be that each compilation run can read / access all snippets, e.g. something like `trace (sys.FileSystem.readDirectory(".."));` would output all snippet uids. snippets would also be able to delete all other snippets (which would be bad). 
we could make snippet folders readonly and mount a dedicated output folder where binaries like `<uid>.hl` or `<uid>.swf` would be generated to, so compilation could only write to that folder and web app would then move binary results to actual snippet folder. 
I guess we would also have to run compilation as a normal user instead of root, otherwise snippets could delete or modify (container's) system files...

I kind of like the response times it offers, though I'm not sure if there are any other security implications or if it is unadvisable to run multiple `docker exec`s on one container in parallel.
what do you think about my idea?

**Comment by RblSb** [comment]
I guess writing files by snippet to personal uid folder will be disabled? Ideally snippet can write files with some limits, and we clear everything at the end of build/competion calls.

**Comment by AlexHaxe** [comment]
well, since it's the same container every time changes made by one stay in-between runs. allowing writes inside programs / snippets folder means that any snippet can write to all snippets folders, because we cannot change volume mapping when using `docker exec` (as far as I know). 
with a new docker container every time you just map its snippet folder and it doesn't see any of the others. that's the nice thing about docker in docker - a shame it's so slow.

my current solution is to have a read-only snippet folder and a read / write output folder where results and binaries go. it involves some copying after a run but it works reasonably fast on my local system. and I guess I can drop a few copy operations, since most result / ouput files are read only once, so there is no need to keep .n or .hl binaries, or stdout / stderr files.

in my next iteration I'm going to just use that output folder, and I will copy everything to it before calling Haxe, and then copy results back to snippets folder. since they are only temporary I can wipe output folders after a every run. 
snippets would then see only other snippets that run in parallel at the same time and potentially could modify sources or result files of those. I'm not sure if that opens up a new path for a malicious actor to mess with things, but at least it's slightly better than having read / write access to all snippets.

**Pull request merged**
