### PR TITLE
use one compiler container

### PR DESCRIPTION
**Pull request by AlexHaxe**

### CODE REVIEW

**Comment by AlexHaxe** [comment]
there is some amount of hard coded paths in Compiler.hx, not sure where to store them or if we should make them configurable. they rely on a certain folders structure in their respective docker containers. so any change in docker also needs changes in Compiler.hx. 
once that's stabilised we can add constants somewhere or maybe put it in environment vars provided docker-compose...

**Comment by RblSb** [comment]
Great job, 600ms for me. Will try to get actual error of my build failure. Also, will remove flash target, probably doesn't make sense anymore, if you are not against. Do you want push access to this repo btw?

**Comment by RblSb** [comment]
Also, ugh... What should be done in practice for this paragraph? Some example would be nice.
> Note: you might have to adjust web container's gid for docker group, to match your outside docker's gid. also make sure outside www-data user is part of docker group.

**Comment by AlexHaxe** [comment]
I was tempted to remove SWF (and maybe neko), question is does it make sense to have multiple targets that all run on backend and just print results? I guess if there is a bug in one platform then it would be nice to be able to showcase it.
the slack people haven't said anything concerning targets. they liked the demo version I've prepared for them. 
I guess we can remove it and if someone complains we can easily add it back in.

push access would be nice. in some distant future we might consider moving it to a more official location, but that is for later.

concerning docker gid, on my Ubuntu system docker group has a different group id / number than the web container's docker group (despite them being the same Ubuntu version). in Dockerfile www-data user inside web container gets added to guest docker group. however docker.sock is owned by root and group docker (host), so when www-data user (guest) tries to access docker.sock mapped through docker-compose it gets access denied because it is neither root nor group docker (host). so what I did was edit `/etc/group` in guest container to set its gid to what my host docker group has. and then I restarted apache `service apache2 restart` to make it use new gid.
after testing again the second part is not really required, as long as gids match. so www-data doesn't have to be in host's docker group.

**Comment by RblSb** [comment]
Checked this command inside web container:
`docker exec -u haxer try-haxe_compiler sh -c "cd /home/haxer/programs/ee348; haxe"`
Output is:
`Failed to call /home/haxer/haxe/versions/4.1.5/haxe because Error: spawnSync /home/haxer/haxe/versions/4.1.5/haxe Unknown system error -8`
Problem is: alpine container calls haxe from host (macos in my case) and this doesn't works for obvious reason. We should call lix inside linux container too for compiler versions setup.

**Comment by AlexHaxe** [comment]
I didn't think of that but yeah makes since, because you filled lixSetup from host by doing `export HAXESHIM_ROOT=$PWD/haxe lix download; etc…`. which is no problem for libs but haxe and neko binaries will be macos ones and thus not work in a linux container.
I guess we can add an image that can be used on non linux systems to setup Haxe binaries. 

on the real system I would probably write a bash script to regularly install new nightles (and clean up old ones).

**Comment by AlexHaxe** [comment]
so far nobody has made the case for keeping SWF, I think you can remove it

do you need help setting up a lix setup container, or are you already looking into it?

**Comment by RblSb** [comment]
Not sure about correct place for this container, probably you can make it better and faster than me, I will be grateful.

**Comment by AlexHaxe** [comment]
ok, I've added a container to docker-compose-all.yml. it will install all haxelibs defined in `lixSetup/haxe_libraries` and download Haxe nightly and 4.1.5.
given it's nature of setting up Haxe and libraries, it doesn't make sense to keep it running in background, so container will do its work and exit.
unfortunately you can't run commands on a stopped container so for anything other you will still have to run the following manually:

```bash
# from try-haxe root folder on host
docker run -it --rm -v $PWD/lixSetup:/srv/lixSetup try-haxe_lix-setup /bin/sh

# inside guest
export HASHSHIM_ROOT=/srv/lixSetup/haxe
lix download haxe 3.4.7
```

**Comment by RblSb** [comment]
`Creating try-haxe_web_1     ... error`
`ERROR: for web  Cannot start service web: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: rootfs_linux.go:59: mounting "/host_mnt/Users/maksim/Projects/git/try-haxe/programs" to rootfs at "/var/lib/docker/overlay2/690fa56f6f88f92d2402dd988e9abfaa4f966e9231db51db7b88e25ef1cd84fd/merged/var/www/html/tmp" caused: mkdir /var/lib/docker/overlay2/690fa56f6f88f92d2402dd988e9abfaa4f966e9231db51db7b88e25ef1cd84fd/merged/var/www/html/tmp: read-only file system: unknown`

**Comment by AlexHaxe** [comment]
hmm, apparently it doesn't like it when parent folder is read-only: https://github.com/RblSb/try-haxe/blob/f5c71f192c53c8325e9053ce9745ffa030dc9c27/docker-compose-all.yml#L8 
so maybe we have to remove `:ro` from that line

or we move tmp folder out of webroot, because there is no reason for it to be there - other than the app using relative paths to access programs/snippets, but since we run in a docker container we have our own folder structure and can mount `programs` folder somewhere else.

**Comment by RblSb** [comment]
Ok, thanks for explanation, feel free to rearrange folder structure then

**Comment by AlexHaxe** [comment]
latest version should work. I've added some constants to hold folder locations in code.

**Comment by RblSb** [comment]
Okay, now with:
`docker exec -u haxer try-haxe_compiler sh -c "cd /home/haxer/programs/EcfdA;  timeout 1s haxe -main Test -cp . --times -D macro-times -dce full -D analyzer-optimize -D analyzer -js run.js > haxe_out 2> haxe_err"`
I'm getting this `haxe_err` file 
`haxelib path: /home/haxer/haxe/versions/4.1.5/haxelib: error while loading shared libraries: libneko.so.2: cannot open shared object file: No such file or directory`
Same error on running `neko` inside of compiler contaner. `realpath /home/haxer/haxe/neko/libneko.so.2` shows that this symlink points to itself, wtf...

I just done `ln -s libneko.so libneko.so.2.3.0; ln -s libneko.so.2 libneko.so.2.3.0` and now compilation of first command works and generates `run.js`, but on web i'm still getting `Build failure` without details.
Throwing `proc.stderr.readAll()` of `new Process(docker, null)` to client shows:
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http:///var/run/docker.sock/v1.40/containers/try-haxe_compiler/json: dial unix /var/run/docker.sock: connect: permission denied`
Oh no that issue exists and there is no copypaste bash fix from readme... And second Alex explanations sounds like horror.

**Comment by AlexHaxe** [comment]
hmm I haven't encountered your neko problem before, not sure if that is because macos or something else... I have it running on both my system and on benchmark server and they didn't have that problem. although I haven't cleaned out lixSetup folder for some time, so maybe something is missing from docker setup.

your docker socket problem sounds like the group id issue I mentioned.
here is what I usually do to fix it:
on host: 
`cat /etc/group | grep docker` write down numer you see (usually third field).
then use `docker exec -it try-haxe_web_1 /bin/bash` to enter web container
inside container:
```bash
apt install vim-tiny
vi /etc/group
# find entry with docker (should be last) and change number to host group id
:wq
service apache2 restart
```
now you should be able to connect to socket from inside web container

**Comment by AlexHaxe** [comment]
note: you'll have to repeat it every time you `docker-compose down/up` your container.

**Comment by RblSb** [comment]
Sorry for delay, had job. This turned out to be unnecessary for the macos host because user groups are not used because of virtualization. Checked all solutions and nothing worked (even installed older docker https://github.com/docker/for-mac/issues/4755), lost latest hope, and actual solution was to open a try-haxe_web_1 shell and run `chmod 777 /var/run/docker.sock`, huh... (doesn't work outside, btw)
Thanks for your patience and help 🎉

**Comment by AlexHaxe** [comment]
kudos for getting it to run on macos!! :tada:

**Pull request merged**
